//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace TimeFree_csharp.KioskServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="kioskSoap", Namespace="http://tempuri.org/")]
    public partial class kiosk : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllSiteAdminsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAWTbyTranOperationCompleted;
        
        private System.Threading.SendOrPostCallback addTFUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback addTFUserJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTranTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTranTypesJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKioskWaitingCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCurrentServingListJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCurrentServingListOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrieveWorkActivitiesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public kiosk() {
            this.Url = global::TimeFree_csharp.Properties.Settings.Default.TimeFree_csharp_KioskServiceReference_kiosk;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event getAllSiteAdminsCompletedEventHandler getAllSiteAdminsCompleted;
        
        /// <remarks/>
        public event getAWTbyTranCompletedEventHandler getAWTbyTranCompleted;
        
        /// <remarks/>
        public event addTFUserCompletedEventHandler addTFUserCompleted;
        
        /// <remarks/>
        public event addTFUserJSONCompletedEventHandler addTFUserJSONCompleted;
        
        /// <remarks/>
        public event getAllTranTypesCompletedEventHandler getAllTranTypesCompleted;
        
        /// <remarks/>
        public event getAllTranTypesJSONCompletedEventHandler getAllTranTypesJSONCompleted;
        
        /// <remarks/>
        public event getKioskWaitingCountCompletedEventHandler getKioskWaitingCountCompleted;
        
        /// <remarks/>
        public event getCurrentServingListJSONCompletedEventHandler getCurrentServingListJSONCompleted;
        
        /// <remarks/>
        public event getCurrentServingListCompletedEventHandler getCurrentServingListCompleted;
        
        /// <remarks/>
        public event retrieveWorkActivitiesCompletedEventHandler retrieveWorkActivitiesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllSiteAdmins", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TFAllSiteAdminsResponse getAllSiteAdmins() {
            object[] results = this.Invoke("getAllSiteAdmins", new object[0]);
            return ((TFAllSiteAdminsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllSiteAdminsAsync() {
            this.getAllSiteAdminsAsync(null);
        }
        
        /// <remarks/>
        public void getAllSiteAdminsAsync(object userState) {
            if ((this.getAllSiteAdminsOperationCompleted == null)) {
                this.getAllSiteAdminsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllSiteAdminsOperationCompleted);
            }
            this.InvokeAsync("getAllSiteAdmins", new object[0], this.getAllSiteAdminsOperationCompleted, userState);
        }
        
        private void OngetAllSiteAdminsOperationCompleted(object arg) {
            if ((this.getAllSiteAdminsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllSiteAdminsCompleted(this, new getAllSiteAdminsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAWTbyTran", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TFGetAWTResponse getAWTbyTran(string tranType) {
            object[] results = this.Invoke("getAWTbyTran", new object[] {
                        tranType});
            return ((TFGetAWTResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAWTbyTranAsync(string tranType) {
            this.getAWTbyTranAsync(tranType, null);
        }
        
        /// <remarks/>
        public void getAWTbyTranAsync(string tranType, object userState) {
            if ((this.getAWTbyTranOperationCompleted == null)) {
                this.getAWTbyTranOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAWTbyTranOperationCompleted);
            }
            this.InvokeAsync("getAWTbyTran", new object[] {
                        tranType}, this.getAWTbyTranOperationCompleted, userState);
        }
        
        private void OngetAWTbyTranOperationCompleted(object arg) {
            if ((this.getAWTbyTranCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAWTbyTranCompleted(this, new getAWTbyTranCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addTFUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TFUserResponse addTFUser(TFUserDetails userDetails) {
            object[] results = this.Invoke("addTFUser", new object[] {
                        userDetails});
            return ((TFUserResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addTFUserAsync(TFUserDetails userDetails) {
            this.addTFUserAsync(userDetails, null);
        }
        
        /// <remarks/>
        public void addTFUserAsync(TFUserDetails userDetails, object userState) {
            if ((this.addTFUserOperationCompleted == null)) {
                this.addTFUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddTFUserOperationCompleted);
            }
            this.InvokeAsync("addTFUser", new object[] {
                        userDetails}, this.addTFUserOperationCompleted, userState);
        }
        
        private void OnaddTFUserOperationCompleted(object arg) {
            if ((this.addTFUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addTFUserCompleted(this, new addTFUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addTFUserJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string addTFUserJSON(string tranType, string mobileNo, string customerName, string remarks) {
            object[] results = this.Invoke("addTFUserJSON", new object[] {
                        tranType,
                        mobileNo,
                        customerName,
                        remarks});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addTFUserJSONAsync(string tranType, string mobileNo, string customerName, string remarks) {
            this.addTFUserJSONAsync(tranType, mobileNo, customerName, remarks, null);
        }
        
        /// <remarks/>
        public void addTFUserJSONAsync(string tranType, string mobileNo, string customerName, string remarks, object userState) {
            if ((this.addTFUserJSONOperationCompleted == null)) {
                this.addTFUserJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddTFUserJSONOperationCompleted);
            }
            this.InvokeAsync("addTFUserJSON", new object[] {
                        tranType,
                        mobileNo,
                        customerName,
                        remarks}, this.addTFUserJSONOperationCompleted, userState);
        }
        
        private void OnaddTFUserJSONOperationCompleted(object arg) {
            if ((this.addTFUserJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addTFUserJSONCompleted(this, new addTFUserJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllTranTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TFTranTypeDtlListResponse getAllTranTypes() {
            object[] results = this.Invoke("getAllTranTypes", new object[0]);
            return ((TFTranTypeDtlListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllTranTypesAsync() {
            this.getAllTranTypesAsync(null);
        }
        
        /// <remarks/>
        public void getAllTranTypesAsync(object userState) {
            if ((this.getAllTranTypesOperationCompleted == null)) {
                this.getAllTranTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTranTypesOperationCompleted);
            }
            this.InvokeAsync("getAllTranTypes", new object[0], this.getAllTranTypesOperationCompleted, userState);
        }
        
        private void OngetAllTranTypesOperationCompleted(object arg) {
            if ((this.getAllTranTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTranTypesCompleted(this, new getAllTranTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllTranTypesJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllTranTypesJSON() {
            object[] results = this.Invoke("getAllTranTypesJSON", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllTranTypesJSONAsync() {
            this.getAllTranTypesJSONAsync(null);
        }
        
        /// <remarks/>
        public void getAllTranTypesJSONAsync(object userState) {
            if ((this.getAllTranTypesJSONOperationCompleted == null)) {
                this.getAllTranTypesJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTranTypesJSONOperationCompleted);
            }
            this.InvokeAsync("getAllTranTypesJSON", new object[0], this.getAllTranTypesJSONOperationCompleted, userState);
        }
        
        private void OngetAllTranTypesJSONOperationCompleted(object arg) {
            if ((this.getAllTranTypesJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTranTypesJSONCompleted(this, new getAllTranTypesJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getKioskWaitingCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TFKioskWaitingCountResponse getKioskWaitingCount(string tranType) {
            object[] results = this.Invoke("getKioskWaitingCount", new object[] {
                        tranType});
            return ((TFKioskWaitingCountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getKioskWaitingCountAsync(string tranType) {
            this.getKioskWaitingCountAsync(tranType, null);
        }
        
        /// <remarks/>
        public void getKioskWaitingCountAsync(string tranType, object userState) {
            if ((this.getKioskWaitingCountOperationCompleted == null)) {
                this.getKioskWaitingCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKioskWaitingCountOperationCompleted);
            }
            this.InvokeAsync("getKioskWaitingCount", new object[] {
                        tranType}, this.getKioskWaitingCountOperationCompleted, userState);
        }
        
        private void OngetKioskWaitingCountOperationCompleted(object arg) {
            if ((this.getKioskWaitingCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKioskWaitingCountCompleted(this, new getKioskWaitingCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCurrentServingListJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCurrentServingListJSON() {
            object[] results = this.Invoke("getCurrentServingListJSON", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCurrentServingListJSONAsync() {
            this.getCurrentServingListJSONAsync(null);
        }
        
        /// <remarks/>
        public void getCurrentServingListJSONAsync(object userState) {
            if ((this.getCurrentServingListJSONOperationCompleted == null)) {
                this.getCurrentServingListJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCurrentServingListJSONOperationCompleted);
            }
            this.InvokeAsync("getCurrentServingListJSON", new object[0], this.getCurrentServingListJSONOperationCompleted, userState);
        }
        
        private void OngetCurrentServingListJSONOperationCompleted(object arg) {
            if ((this.getCurrentServingListJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCurrentServingListJSONCompleted(this, new getCurrentServingListJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCurrentServingList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TFCurrentServingListResponse getCurrentServingList() {
            object[] results = this.Invoke("getCurrentServingList", new object[0]);
            return ((TFCurrentServingListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getCurrentServingListAsync() {
            this.getCurrentServingListAsync(null);
        }
        
        /// <remarks/>
        public void getCurrentServingListAsync(object userState) {
            if ((this.getCurrentServingListOperationCompleted == null)) {
                this.getCurrentServingListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCurrentServingListOperationCompleted);
            }
            this.InvokeAsync("getCurrentServingList", new object[0], this.getCurrentServingListOperationCompleted, userState);
        }
        
        private void OngetCurrentServingListOperationCompleted(object arg) {
            if ((this.getCurrentServingListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCurrentServingListCompleted(this, new getCurrentServingListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retrieveWorkActivities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retrieveWorkActivities(int TrackNumber) {
            object[] results = this.Invoke("retrieveWorkActivities", new object[] {
                        TrackNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retrieveWorkActivitiesAsync(int TrackNumber) {
            this.retrieveWorkActivitiesAsync(TrackNumber, null);
        }
        
        /// <remarks/>
        public void retrieveWorkActivitiesAsync(int TrackNumber, object userState) {
            if ((this.retrieveWorkActivitiesOperationCompleted == null)) {
                this.retrieveWorkActivitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveWorkActivitiesOperationCompleted);
            }
            this.InvokeAsync("retrieveWorkActivities", new object[] {
                        TrackNumber}, this.retrieveWorkActivitiesOperationCompleted, userState);
        }
        
        private void OnretrieveWorkActivitiesOperationCompleted(object arg) {
            if ((this.retrieveWorkActivitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveWorkActivitiesCompleted(this, new retrieveWorkActivitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFAllSiteAdminsResponse {
        
        private TFSiteAdminDetails[] siteAdminListField;
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public TFSiteAdminDetails[] SiteAdminList {
            get {
                return this.siteAdminListField;
            }
            set {
                this.siteAdminListField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFSiteAdminDetails {
        
        private string adminIDField;
        
        private string mobileNoField;
        
        private string remarksField;
        
        private string statusField;
        
        private string filler1Field;
        
        private string filler2Field;
        
        /// <remarks/>
        public string adminID {
            get {
                return this.adminIDField;
            }
            set {
                this.adminIDField = value;
            }
        }
        
        /// <remarks/>
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string filler1 {
            get {
                return this.filler1Field;
            }
            set {
                this.filler1Field = value;
            }
        }
        
        /// <remarks/>
        public string filler2 {
            get {
                return this.filler2Field;
            }
            set {
                this.filler2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFCurrentServing {
        
        private int servingIDField;
        
        private string tranTypeField;
        
        private string queueNoField;
        
        private int tFUserIDField;
        
        private string customerNameField;
        
        private string mobileNoField;
        
        private string counterNoField;
        
        private string timeStampField;
        
        /// <remarks/>
        public int ServingID {
            get {
                return this.servingIDField;
            }
            set {
                this.servingIDField = value;
            }
        }
        
        /// <remarks/>
        public string tranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
        
        /// <remarks/>
        public string queueNo {
            get {
                return this.queueNoField;
            }
            set {
                this.queueNoField = value;
            }
        }
        
        /// <remarks/>
        public int TFUserID {
            get {
                return this.tFUserIDField;
            }
            set {
                this.tFUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string counterNo {
            get {
                return this.counterNoField;
            }
            set {
                this.counterNoField = value;
            }
        }
        
        /// <remarks/>
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFCurrentServingListResponse {
        
        private TFCurrentServing[] currentServingListField;
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public TFCurrentServing[] CurrentServingList {
            get {
                return this.currentServingListField;
            }
            set {
                this.currentServingListField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFKioskWaitingCountResponse {
        
        private string tranTypeField;
        
        private int waitingCountField;
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public string tranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
        
        /// <remarks/>
        public int waitingCount {
            get {
                return this.waitingCountField;
            }
            set {
                this.waitingCountField = value;
            }
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFTranTypeDetails {
        
        private string tranTypeField;
        
        private string groupTypeField;
        
        private string infoField;
        
        private int prefixField;
        
        private string statusField;
        
        private int sLAField;
        
        private string iconNameField;
        
        /// <remarks/>
        public string tranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
        
        /// <remarks/>
        public string groupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        public int prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int SLA {
            get {
                return this.sLAField;
            }
            set {
                this.sLAField = value;
            }
        }
        
        /// <remarks/>
        public string iconName {
            get {
                return this.iconNameField;
            }
            set {
                this.iconNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFTranTypeDtlListResponse {
        
        private TFTranTypeDetails[] transactionTypesField;
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public TFTranTypeDetails[] TransactionTypes {
            get {
                return this.transactionTypesField;
            }
            set {
                this.transactionTypesField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFUserResponse {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        private TFUserDetails userDetailsField;
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        public TFUserDetails UserDetails {
            get {
                return this.userDetailsField;
            }
            set {
                this.userDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFUserDetails {
        
        private string userReferenceNoField;
        
        private string tranTypeField;
        
        private string mobileNoField;
        
        private string customerNameField;
        
        private string queueNoField;
        
        private string remarksField;
        
        private string awtField;
        
        private string dateServedField;
        
        private string dateCalledField;
        
        private string smsTimeField;
        
        /// <remarks/>
        public string userReferenceNo {
            get {
                return this.userReferenceNoField;
            }
            set {
                this.userReferenceNoField = value;
            }
        }
        
        /// <remarks/>
        public string tranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
        
        /// <remarks/>
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string queueNo {
            get {
                return this.queueNoField;
            }
            set {
                this.queueNoField = value;
            }
        }
        
        /// <remarks/>
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public string awt {
            get {
                return this.awtField;
            }
            set {
                this.awtField = value;
            }
        }
        
        /// <remarks/>
        public string dateServed {
            get {
                return this.dateServedField;
            }
            set {
                this.dateServedField = value;
            }
        }
        
        /// <remarks/>
        public string dateCalled {
            get {
                return this.dateCalledField;
            }
            set {
                this.dateCalledField = value;
            }
        }
        
        /// <remarks/>
        public string smsTime {
            get {
                return this.smsTimeField;
            }
            set {
                this.smsTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TFGetAWTResponse {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        private string aWTMinutesField;
        
        private int cutoffStatusField;
        
        private string sendernameField;
        
        private string compIDField;
        
        private string branchIDField;
        
        private string countryField;
        
        private string trigger_valueField;
        
        private int trigger_timeField;
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        public string AWTMinutes {
            get {
                return this.aWTMinutesField;
            }
            set {
                this.aWTMinutesField = value;
            }
        }
        
        /// <remarks/>
        public int CutoffStatus {
            get {
                return this.cutoffStatusField;
            }
            set {
                this.cutoffStatusField = value;
            }
        }
        
        /// <remarks/>
        public string sendername {
            get {
                return this.sendernameField;
            }
            set {
                this.sendernameField = value;
            }
        }
        
        /// <remarks/>
        public string compID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
        
        /// <remarks/>
        public string branchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string trigger_value {
            get {
                return this.trigger_valueField;
            }
            set {
                this.trigger_valueField = value;
            }
        }
        
        /// <remarks/>
        public int trigger_time {
            get {
                return this.trigger_timeField;
            }
            set {
                this.trigger_timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAllSiteAdminsCompletedEventHandler(object sender, getAllSiteAdminsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllSiteAdminsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllSiteAdminsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TFAllSiteAdminsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TFAllSiteAdminsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAWTbyTranCompletedEventHandler(object sender, getAWTbyTranCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAWTbyTranCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAWTbyTranCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TFGetAWTResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TFGetAWTResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addTFUserCompletedEventHandler(object sender, addTFUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addTFUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addTFUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TFUserResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TFUserResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addTFUserJSONCompletedEventHandler(object sender, addTFUserJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addTFUserJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addTFUserJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAllTranTypesCompletedEventHandler(object sender, getAllTranTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTranTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTranTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TFTranTypeDtlListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TFTranTypeDtlListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAllTranTypesJSONCompletedEventHandler(object sender, getAllTranTypesJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTranTypesJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTranTypesJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getKioskWaitingCountCompletedEventHandler(object sender, getKioskWaitingCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKioskWaitingCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKioskWaitingCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TFKioskWaitingCountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TFKioskWaitingCountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getCurrentServingListJSONCompletedEventHandler(object sender, getCurrentServingListJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCurrentServingListJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCurrentServingListJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getCurrentServingListCompletedEventHandler(object sender, getCurrentServingListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCurrentServingListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCurrentServingListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TFCurrentServingListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TFCurrentServingListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void retrieveWorkActivitiesCompletedEventHandler(object sender, retrieveWorkActivitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveWorkActivitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveWorkActivitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591